### ISSUE TITLE
Bouncing while landing records multiple landings

### ISSUE THREAD

**Issue by lg** [scelts/msfslandingrate#11]
possible to only record the first hit to the ground? sometimes i'll bounce around a bit which records multiple landings. workaround if it's not possible to cleanly get this data, maybe don't record 2 landings in a 30 second window?

example:
<img width="415" alt="Screenshot 2020-10-31 134501" src="https://user-images.githubusercontent.com/181018/97789638-51acae80-1b7f-11eb-9bcf-327c3e80cbce.png">

**Comment by scelts** [comment]
Yes, this is on the list. My idea was not to record landings after the first one, which are less than... 300m apart? Or 30s, depending what's easier to do, it's the same effect.
Hopefully, I get some time to work on this and a few other things in the next couple of days.

**Comment by scelts** [comment]
version 1.1.0 should fix this
