### ISSUE TITLE
failed to start the app

### ISSUE THREAD

**Issue by n30a5tr0** [scelts/msfslandingrate#12]
Hello, I am unable to start the app, v. 1.0.0, nor older version with or without msfs2020 running. Version of sim: 1.10.8.0 (I did not test it on older version of the sim). Sadly, app is unable to create a log as well...
![gees_1 0 0_error](https://user-images.githubusercontent.com/25278099/97801286-d957f300-1c3b-11eb-92a3-363703208703.jpg)

**Comment by scelts** [comment]
This can happen due to the antivirus blocking it. 
For some reason, it seems that the app just cannot access it's own folder.
Can you maybe just try moving it to another folder, and trying it then?

**Comment by n30a5tr0** [comment]
> This can happen due to the antivirus blocking it.
> For some reason, it seems that the app just cannot access it's own folder.
> Can you maybe just try moving it to another folder, and trying it then?

Thank you very much :) I did not realised I was trying to run it from "desktop" folder and not some proper location :) Running fine now, thanks! =)

**Comment by scelts** [comment]
No problem! Glad you like it.
