### ISSUE TITLE
Gees crashes before the window opens

### ISSUE THREAD

**Issue by LucaJC** [scelts/msfslandingrate#16]
I´m extracting the zip file (not to the desktop). Im launching gees.exe, the icon appears in the icon tray and dissapeares after approximately 2-5 seconds. The window in the right bottom corner doesnt open at all. And that happens all the time. What am I doing wrong, so that i can´t use gees. I had installed gees a while ago but deleted it, to install a newer version. It worked fine for quite a while but suddently the aforementioned issue appeared. If you need more informations like the log, let me know how to find it. 
Kind Regards

**Comment by scelts** [comment]
There should be a log.txt file in the folder where the app is, if some error happened.

**Comment by LucaJC** [comment]
I attached a video of the issue. In the folder where the gees.exe is, is no log.
http://www.filedropper.com/2020-12-0800-36-54
Kind Regards

**Comment by scelts** [comment]
Ok, I believe there's something that force-closes the app, otherwise there will be at least some error popping up. 
I'm looking at the antivirus there. Is there any reports of "threats" there with it?
Maybe try to close it shortly and then try to run it, just to isolate if it's that. I'm looking at the code now, and it should not fail as graciously as this, without popping up the exception.

**Comment by LucaJC** [comment]
I´ve added the program.exe to the whitelist of avira and even deactivided the whole avira antiviurs programm but gees still crashes. The antivirus didnt showed any threats and there were no files, at any time, in it. How can I run gees an close it? It´s closing itself before I can select it or I cant interact with the icon in the task bar. It doesnt even appear in the task manager while i´m opening it.

**Comment by scelts** [comment]
well, this is not good, as now I have no idea what could be the problem.
try to move it to a different folder. although I'm just babbling this, have no reasonable explanation why this would fix it :)

**Comment by LucaJC** [comment]
I'll try that later. I also noticed, that the PrettyBin library isn't in the lib folder. Does that help. Maybe I'll try to reinstall visual studios and the .net framework, but wich version does I need and how do I find them (e.g. Visual studio .../2019/2020 and how do I install the .net framework 4.7?) 
Kind regards

**Comment by scelts** [comment]
you dont need visual studio, just the .net framework >= 4.7.
I doubt it's that as it would definitely trigger an error.

prettybin is not a runtime dependency, it just helps to move these dll's from the main app folder to another folder (lib). But this might be a good idea: are the files in the zip file the same as the ones in the folder? Maybe a dependency got blocked by the antivirus?
But it's probably not an antivirus.

**Comment by LucaJC** [comment]
Yes they were, but i have breaking news, every version under, including, 0.2.0 worked just fine for me. I tested it right now, in the version 0.2.0 the window opens without any problem, and the programm was working fine. The antivirus was activieded. I then tried the 1.1.0 and it crashed again. So every version over 0.2.0 doesnt work for me
Kind regards

**Comment by LucaJC** [comment]
So i tried another thing. I created a new folder, copied everything from the gees_1.1.0 folder and placed that into the new created folder. After that i deleted everything in the lib folder of the new created folder, with exception of the gees.pdb and copied all the things that were in the lib folder from gees_0.2.0 with exception of the gees.pdb into the lib folder of the new created folder, in wich was only the gees.pdb from version 1.1.0 left. It gave me that error in the log, maybe it can help you. [log.txt](https://github.com/scelts/gees/files/5661146/log.txt)
Kind regards

**Comment by scelts** [comment]
that's not gonna work. 
the difference after 0.2.0 is that the app is not windows forms, but wpf, and there's a log file that should be stored in Documents folder as csv file.

can you run these two commands in the power shell and tell me the output:
1:
```
(Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release -ge 461808
```
output should be "True"

2:
```
[environment]::getfolderpath(“mydocuments”)
```
output should be your "mydocuments" folder path

**Comment by LucaJC** [comment]
![Unbenannt](https://user-images.githubusercontent.com/75641030/101789550-bacdfd00-3b01-11eb-8c6e-5d891baa71ac.JPG)
The Powershell gives me the exact outcome as you wrote. In the MyMFS2020Landing-Gees folder in Documents is only the Landing.v3.csv file: [Landings.v3.csv.zip](https://github.com/scelts/gees/files/5673682/Landings.v3.csv.zip)
Do you already know what the issue is?
Kind regards

**Comment by LucaJC** [comment]
I´ve found the Problem. Now Gees 1.10 works fine. In my Case i had to unistall the Rivatuner Statistics Server, located in the Path of the Msi Afterburner, because a Process named LedKeeper.exe blocked my Java interface and Control Center (in fact it blocked whole java/java.exe/javaw.exe/... and all that stuff, two Programming Applications based on Java, the Discord overlay, Gees, and some other Stuff. After researching and trying everything out a loooong time, I came arround to setup a Profile in the Event Manger from Windows itself, witch showed me all Error and Information messages on my Pc. Quick look inside of that gave me the Path of the Process and the name of it (LedKeeper.exe / rivatuner statistics server). In fact it created in the past Month more than 150.000 Error Messages. After deleting it, Everything came instantly back to live, even without restarting the Pc. 
Shocked that only one little Process can mess up half of the Pc, but thanks for your help and kind regards,
Luca
