### ISSUE TITLE
Bug: My Landings - Sort by time, sort in strange order

### ISSUE THREAD

**Issue by Leachy75** [scelts/msfslandingrate#17]
Firstly let me say thank you for a wonderful little program! I love its simplicity and the displaying of the landing data as a popout is a superb touch!

BUG:
In the My Landings window, if I click the "Time" column header, the items are sorted by time and date 
BUT they are sorted with ascending dates and descending times
OR they are sorted with descending dates and ascending times.
This does not keep them in the order I would like - I would like to see them in the order they happened, top to bottom, earliest to latest or latest to earliest if I click again.

after further examination, thats not quite it but it looks pretty close to that 
they appear to be sorted purely as numbers and not as dates and times,

I believe this will happen in Visual Studio if you add dates and times as a "string" object to a column.
If you are adding dateTime objects to a column, add them as dateTime objects and dont convert them to strings and the sorting will take care of itself. You just have to set the columns format to dateTime. 

Also: can we have the dates localised! In Australia the day comes before the month and its confusing to see it represented in any other format  eg..  DD/MM/YYYY  where your program displays MM/DD/YYYY.
This may be fixed by the previous bug fix (I think Visual Studio dateTime columns are localised automatically).

PS: keep up the good work!

**Comment by scelts** [comment]
Fixes
