### ISSUE TITLE
Sorting data by landing rate returns incorrect results

### ISSUE THREAD

**Issue by anish3343** [scelts/msfslandingrate#23]
Sorting previous landing data by landing rate in the integrated tool shows an incorrect order [See screenshot below]:

![image](https://user-images.githubusercontent.com/43268896/115134755-f9f4e900-9fe0-11eb-942c-a89e0fa5ceaa.png)

It appears that landing rates are treated as strings, rather than numbers. This issue seems at least partially related to issue #17 .

**Comment by scelts** [comment]
Fixed
