### ISSUE TITLE
Date sorting is broken with the new year due to sorting by month before year

### ISSUE THREAD

**Issue by mshostack** [scelts/msfslandingrate#29]
I was wondering why my recent landings were not showing when I have my landings table sorted by `Time`. The last one displayed was from 12/31/21. I sorted by `Time` again, and suddenly my flights from 2022 are visible, but only in descending. When I sort by ascending (so as to make my most recent flight display at the top), it moves all of the 2022 flights at the bottom because it seems to first sort by month, not year.

The expected behavior would be to first sort by year, then month, then date.

![image](https://user-images.githubusercontent.com/51968672/150282826-f3ad17a6-c301-4cd7-af4d-1f7bc31f9af2.png)

**Comment by smitty97** [comment]
came here to report this also

**Comment by scelts** [comment]
Fixed
