### ISSUE TITLE
Suggestion: Persist last landing?

### ISSUE THREAD

**Issue by shanna** [scelts/msfslandingrate#3]
I would like a way to recall my last landing as quite often I'm still dealing with the tower & instruments on touchdown and the popup disappears before I get a chance to really see stats other than the emoji face that tells me how bad my landing was.

This could be achieved in one of a few ways:
* Popup duration in seconds configuration (zero being infinite with click to close).
* Display the last landing if you hover over the taskbar icon.
* Shortcut key.

I haven't looked at the MSFS2020 plugin API or what's possible yet but if you have a preference I can probably Google enough C# to submit a pull request if you have a preference.

**Comment by scelts** [comment]
I think an easy fix would be the duration setting with an option to leave it visible until it's clicked?

**Comment by g0per** [comment]
Can you add a *recall last report* button? I think that makes the user customization requirements easier.

**Comment by scelts** [comment]
Yes. I was planning also to keep the log of all the landings in some format. But before going into the log, such a simple "show again" solution could be nice:
So far I have a few ideas for this, without going into the log
- Timer selection how long it's open and possibility not to auto-close. Cons: you still don't have recall after.
- General key listener, when you press a predetermined key, it shows the last. I already tried a version with this. Cons: Well, it would listen for keys all the time. If I was an antivirus I wouldn't like such an app.
- A small tab peering always on the side, one can click to get the info. Cons: it's gonna be there all the time.

**Comment by g0per** [comment]
I was thinking about the taskbar icon and its popup window so it was already there. Is it feasible?

**Comment by HugoTro** [comment]
a log would be nice because right now we can't really compare the rate of our landings...

**Comment by scelts** [comment]
> I was thinking about the taskbar icon and its popup window so it was already there. Is it feasible?

Sure, now that I think about it I'll take a day or two and just do the proper log, saving everything, sorting by date, show in a table, and there we go. It kind of solves all the problems mentioned here.

**Comment by scelts** [comment]
Both log, and persist last landing implemented in https://github.com/scelts/gees/releases/tag/0.3.1
