### ISSUE TITLE
Incorrect speeds in the LOG file

### ISSUE THREAD

**Issue by HugoTro** [scelts/msfslandingrate#7]
Airspeed not corresponding to the real airspeed on touchdown, and the indicated crosswinds are the airspeed of the plane
![gees](https://user-images.githubusercontent.com/64845965/95987334-93bbbd80-0e27-11eb-8b04-afd198854a8f.jpg)

and yes these are very very bad landings

**Comment by scelts** [comment]
Wow, seems that many of the things are wrong: headwind is not correct too I guess?
Did you edit the Landings.v1.csv file maybe - opened it in excel, changed columns, saved it etc? Anything else you modified or something?

I'm asking cause I have no idea how this happened.

**Comment by scelts** [comment]
running simulation at half rate/ 2x rate etc? Very low FPS? Anything that's not usual?

**Comment by HugoTro** [comment]
i didn't do anything on the csv file, didn't open it, didn't even opened the location of the file in file explorer

**Comment by HugoTro** [comment]
i'll retest to see

**Comment by HugoTro** [comment]
i tested again and... it didn't record my landing it the TBM930

**Comment by HugoTro** [comment]
and there is a red strip that is staying on the left of my screen

**Comment by scelts** [comment]
that's supposed to be there, you can click to show.
can you give me some more info on anything unusual in your setup? also, if there is a log.txt file in the app folder, please paste it here.

**Comment by HugoTro** [comment]
what i find wierd is that only the speeds in the log are messed up

**Comment by scelts** [comment]
I think I have an idea what is it!
Can you please help me and check the Control Panel -> Clock and Region -> Region -> Additional settings -> Decimal symbol
![image](https://user-images.githubusercontent.com/30724123/95994456-9d95ee80-0e30-11eb-9985-4aaedefa3a90.png)

I assume it's a comma (,)

Also please check the Documents\MyMSFS2020Landings-Gees csv file. You'll probably have more columns in values than titles.

Note: https://stackoverflow.com/questions/3135569/how-to-change-symbol-for-decimal-point-in-double-tostring

**Comment by scelts** [comment]
No need to check, it's 100% this error.... I'm new with all this c# app dev.
I'll fix it in the next version, sorry for this.
The workaround, for now, is to change this setting to dot ( . ), delete the existing log, and restart the app. Or just leave it, I'll push the new version later during the day. But the log is gonna stay bad, so you'll lose the landings you did, sorry.

**Comment by HugoTro** [comment]
yeah it's a comma on my pc

**Comment by HugoTro** [comment]
> No need to check, it's 100% this error.... I'm new with all this c# app dev.
> I'll fix it in the next version, sorry for this.
> The workaround, for now, is to change this setting to dot ( . ), delete the existing log, and restart the app. Or just leave it, I'll push the new version later during the day. But the log is gonna stay bad, so you'll lose the landings you did, sorry.

don't worry for my landings, these ones were to test your app, and as you can see, they're bad anyway...

**Comment by scelts** [comment]
Why bad, standard Ryanair landing :)

Thanks for the reporting, it's a really stupid error, but a tough one to catch.

**Comment by scelts** [comment]
0.3.2 should hopefully fix this.
